---
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.security.autoconfiguration.enabled: true
xpack.security.http.ssl:
  enabled: true
xpack.security.transport.ssl:
  enabled: true
